### ISSUE TITLE
Відображення міток різних кольорів

### ISSUE THREAD

**Issue by KristiSik** [KristiSik/SAO-keep#2]
Як, користуючись Google Map API, використовувати мітки різних кольорів?

**Comment by VoznyakR** [comment]
Створи власні, завантаж їх на сервер, а звідти вже вказуй шлях до них у полі Icon

**Comment by KristiSik** [comment]
@VoznyakR , так, але я б хотів використовувати стандартні мітки, які надає Google.Maps

**Comment by VoznyakR** [comment]
Тоді ось:
http://maps.google.com/mapfiles/ms/icons/red-dot.png
http://maps.google.com/mapfiles/ms/icons/green-dot.png
http://maps.google.com/mapfiles/ms/icons/blue-dot.png

**Comment by KristiSik** [comment]
Дякую!
